### ISSUE TITLE
Create new section for general guidance and philosophy 

### ISSUE THREAD

**Issue by kathrynmohror** [pmix/governance#6]
We want to create a section in the governance document that outlines the intended philosophy or best practices that the ASC should follow. This section is not meant to be binding in the sense of rules, but to provide guidance to the ASC in making decisions that do not have hard and fast rules. 

The first piece of content for this section would give guidance for timings of major releases. We want to ensure that additions/modifications/deprecations to the standard are reflected in major releases in a timely manner. An idea was floated to require a new release each year, or perhaps triggered only when changes are made. However, we decided we don't want to force releases when only small changes are made (e.g. typo fixes). Thus, we thought that providing guidance to the release manager and ASC would ensure that the group prioritizes timely releases when they are warranted.

Suggested changes: 
- New section 1.2 "ASC Guidance"  ("The Standardization Process" becomes section 1.3)
- New section 1.2.1 "Release Schedule"
- Content: As described in Section 1.1.6, the schedule of major releases of the PMIx Standard is determined by the Release Managers in coordination with other members of the ASC. There is no prescribed major release schedule that the Release Managers must follow. However, the Release Managers will prioritize timely releases of substantive changes to the PMIx Standard. Substantive changes include: new APIs, keys, or other text in the standard; deprecated or removed APIs, keys, or other text in the standard; alterations of APIs or keys; and alterations of text that result in changed meaning or clarifications. The Release Managers will prioritize major releases of the standard over waiting for additional changes that are in progress but not yet accepted by the ASC.

**Comment by jjhursey** [comment]
Per meeting on Sept. 6, 2019
 * General support for this item.
 * Need to add some leading text for the new section highlighting that it is nonbinding guidance.
 * Kathryn will work on a PR form of this proposal for next meeting.
   * We plan to have this ready for the ASC quarterly meeting.

**Comment by kathrynmohror** [comment]
Implemented in PR https://github.com/pmix/governance/pull/7

**Comment by jjhursey** [comment]
PR #7 has been merged!
